steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - build
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:latest'
      - '--network=cloudbuild'
      - '--publish'
      - '--path=.'
      - '--env=GOOGLE_ENTRYPOINT=node .next/standalone/server.js'
      - '--env=NEXT_PUBLIC_BASE_URL=$_NEXT_PUBLIC_BASE_URL'
      - '--env=NEXT_PUBLIC_BASE_URL_OFFICE=$_NEXT_PUBLIC_BASE_URL_OFFICE'
    id: Buildpack

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

substitutions:
  _AR_HOSTNAME: asia-southeast1-docker.pkg.dev
  _SERVICE_NAME: fintra-landing
  _NEXT_PUBLIC_BASE_URL: https://sdt.fintra.com.bd/api
  _NEXT_PUBLIC_BASE_URL_OFFICE: https://office-testb.fintra.com.bd/api

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
